'use client';

// import type { Metadata } from 'next';

import './globals.scss';
import { Provider } from 'react-redux';
import { store } from '@/store/config/store';
import { AuthProvider } from '@/hooks/AuthContext';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Provider store={store}>
          <AuthProvider>{children}</AuthProvider>
        </Provider>
      </body>
    </html>
  );
}
